
#ifndef GSSAPI_OIDC_CONSTANTS_H
#define GSSAPI_OIDC_CONSTANTS_H

#define PORT_NUMBER 8080
#define MAX_CONNECTIONS 100
#define BUFFER_SIZE 1000
#define STRINGS_SIZE 1000
#define OIDC_MECHANISM 15
#define MINOR_STATUS_OK 5

#endif